import {  Poppins } from "next/font/google";
import {  Bebas_Neue } from "next/font/google";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./style.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["300","400","500","600","700"],variable:'--poppins',display: 'swap'});
const bebasNeue = Bebas_Neue({ subsets: ["latin"],weight: ["400"],variable:'--bebasneue',display: 'swap'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"
     className={`${poppins.variable} ${bebasNeue.variable}`}
     >
      <body>{children}</body>
    </html>
  );
}
